name: stethophone
description: Stethophone
publish_to: 'none'
version: 3.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_settings: ^5.1.1
  async: ^2.11.0
  auto_route: ^7.8.4
  connectivity_plus: ^4.0.2
  device_info_plus: ^9.1.0
  dio: ^5.3.3
  easy_localization_loader: ^2.0.0
  easy_localization: ^3.0.3
  flutter_branch_sdk: ^7.0.1
  flutter_cache_manager: ^3.3.1
  flutter_native_splash: ^2.3.5
  flutter_pdfview: ^1.3.2
  flutter_riverpod: ^2.4.6
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.1
  flutter_sound_lite: ^8.5.0
  flutter_svg: ^2.0.9
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  in_app_purchase: ^3.1.13
  in_app_review: ^2.0.6
  intl: ^0.18.0
  json_annotation: ^4.8.1
  local_auth: ^2.1.7
  logger: ^1.4.0
  open_mail_app: ^0.4.5
  overlay_support: ^2.1.0
  package_info_plus: ^4.2.0
  page_view_indicators: ^2.0.0
  path: ^1.8.3
  permission_handler: ^11.0.1
  pinput: ^3.0.1
  pub_semver: ^2.1.4
  rxdart: ^0.27.7
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  skeletons: ^0.0.3
  sqflite_sqlcipher: ^2.2.1
  tuple: ^2.0.2
  uni_links: ^0.5.1
  url_launcher: ^6.2.1
  uuid: ^3.0.7
  vibration: ^1.8.3
  youtube_player_flutter: ^8.1.2
  path_provider: ^2.1.3

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  faker: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lint: ^2.2.0
  mockito: ^5.4.2
  test_cov_console: ^0.2.2
  test: ^1.24.3

dependency_overrides:
  sqflite:
    git:
      url: https://bitbucket.org/sparrowacoustics/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/guides/
    - assets/translations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/logo.png
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/**_page.dart
      auto_route_generator:auto_router_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/app_router.dart
